[project]
name = "selenium-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.11"
dependencies = [
    "asyncio>=4.0.0",
    "fastapi>=0.116.1",
    "selenium>=4.35.0",
    "uvicorn>=0.35.0",
]
